require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Say hello to the user."
task :greet do
  puts "Hello there!"
end
